baseURL = "https://bargavkondapu.com"
languageCode = "en-us"
title = "Bargav Kondapu"
tags=["leadership", "motivation","mythology", "philosophy"]
categories=["interactions","technology","development","tutorial", "blogs", "drupal", "emberjs", "web-development","angularjs"]
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[params]
  description = "Hi! I am Bargav. I develop websites and help organizations establish their digital presence. I like sharing knowledge and inspirations, and having deep conversations with people."
  site_image = "https://bargavkondapu.com/images/bk-profile.jpg"
  default_image = "/images/laptop-journal.jpeg"

  author = "Bargav Kondapu"
  author_description = "Hi! I am Bargav. I develop websites and help organizations establish their digital presence. I like sharing knowledge and inspirations, and having deep conversations with people."
  author_image="/images/bk-profile-sm.jpeg"
  copyright = "Â© 2018 Bargav Kondapu "

  no_title_pages=["notes","interactions"]

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 100

  [[menu.main]]
    name = "Notes"
    url = "/notes"
    weight = 99

  [[menu.main]]
      name = "Interactions"
      url = "/interactions"
      weight = 98

  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 97

  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 96
